COLUMNS = {
    "terms": [
        "term",
        "termtitle",
        "startdate",
        "enddate",
        "objectclass"
    ],
    "courses": [
        "course",
        "subject",
        "subjecttitle",
        "catalog",
        "coursetitle",
        "coursedescription",
        "facultycode",
        "faculty",
        "departmentcode",
        "department",
        "career",
        "units",
        "asstring",
        "objectclass",
        "term"
    ],
    "classes": [
        "class",
        "section",
        "component",
        "classtype",
        "classstatus",
        "enrollstatus",
        "capacity",
        "startdate",
        "enddate",
        "session",
        "campus",
        "location",
        "autoenroll",
        "classtopic",
        "classnotes",
        "consent",
        "gradingbasis",
        "instructionmode",
        "units",
        "classurl",
        "instructoruid",
        "examstatus",
        "examdate",
        "examstarttime",
        "examendtime",
        "examlocation",
        "asstring",
        "objectclass",
        "course",
        "term",
    ],
}
print("terms: " + ', '.join(COLUMNS['terms']))
print("courses: " + ', '.join(COLUMNS['courses']))
print("classes: " + ', '.join(COLUMNS['classes']))
